apply plugin: 'maven-publish'

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())
def gitLabKey = properties.getProperty('gitLabKey')

// get git lab key in git lab, public libs project
// run gradle task maxhelper build/build, then publishing/publish
// for local update, choose publishToMavenLocal

publishing {
    publications {
        library(MavenPublication) {
            groupId "com.maxdota"
            artifactId "core"
            version "0.0.7-3"
            artifact "$buildDir/outputs/aar/core-debug.aar"
        }
    }
    repositories {
        maven {
            url "https://gitlab.com/api/v4/projects/26576533/packages/maven"
            credentials(HttpHeaderCredentials) {
                name = "Private-Token"
                value = gitLabKey
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}

tasks.withType(PublishToMavenRepository).configureEach {
    dependsOn 'build'
}

tasks.withType(PublishToMavenLocal).configureEach {
    dependsOn 'build'
}
